language: generic
sudo: required
services:
  - docker

deploy:
  provider: packagecloud
  repository: "ci"
  username: "ergw"
  token:
    secure: "kV917u6IeXIr64e9gf/gFs9L/+SzQoEZFCyoby530oAq80qtF+lCsQ1E5c/ihJimazwK5c+261ho3OdbFjQhy/SX9ufmXJj2TNAtPYL3jCC6R77qnyaXJiHIyially1k3kcFsi7ZcBItGJwXK8RDRCxBPQ0Z8VVvs+1oNvVtVAQe9Un8JcklduZH6sDgqsp1ZuUWE7Pdg7kjeNEfHzxaD4YftXyiGqtAMpmfnRRlg3eM/8JE+b8pQTlXABUoleRXfIZtzpY+QBIscOaKBu66zF2djMcZgc4A1cLUVgGHY0QgOeDPcTR+5V906TyngKGV92I4R+cfz/gFayPsIdbzEwfBFQpfSPxyyey8MM87Ge5WaWGGGznfM+P1iVoWX19j6K9/aQzBjLA8u2VYOqLpEolS+zT91guv1WG4+8LzKFCAaVWNmKUgw4aSr+Ff9CZy8Z4Lzp+W6hHRU5MBWyH8YsZrI5ngXCuMQNzQ8NVhfmrxmwJfuUv7Hb44cJvoLBsIRv6d3TutwLZSxSUAM6rbuL9IsCeVXLoqKBGk6gQc1TvY0GrszW/O6Z2yKOYGyl4mCUaE+u9X62zZApLYPJsYWPcQPumILLzh/2UgXQRHwxa5fvvffgNp8OxqG+V3xDElRC3wd57ub2i1/f6pe5IrNb5jtFWredeY7zgJCpfHAHI="
  dist: "ubuntu/xenial"
  skip_cleanup: true
  package_glob: artifacts/*.deb

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts
  - docker build -t ergw -f priv/Dockerfile priv

script:
  - export SHORT_COMMIT_ID=$(git rev-parse --verify --short $TRAVIS_COMMIT)
  - debchange -m -l "+$TRAVIS_JOB_NUMBER+git$SHORT_COMMIT_ID" 'Automatically built'
  - mkdir artifacts
  - docker run -v `pwd`:/build ergw
    sh -c "
      dpkg-buildpackage -b -uc && cp ../*deb artifacts
    "

notifications:
  slack:
  - secure: "bwk2/vd/EcAEzb9p31G+eI6VscKTlpX5glh2oL31M/5QmWgjPpa1tHwLck11HjNHBdKcnQ2Po9axTn09gMnUGP9XpnYgvmCdx10Qnry4S1O0i2DDICW8txXQY7POUoFGAlbfIVLevsx4Z4RJn1lqivRfQ+t6eHVa8uYobjpwrymg9Xgtq7+nIk08zXZn6OIRPJZT+YdmJKA74SGk/l6FAoqhVNjDVd6IgmAuYTUeqwQfl3Y4dxPCgqeJTovyb0z79dHSGmqSQxqw9sMAE7U+fq8b2c8BvUOb5dJp/Kd2HyNLgKSnt0KtcvKKnRhwYCLorctc9hoYnl9dvfwqm1UgR9mdWDDbu470j4xj5s8HWr1+zCqw2eSooBLPRbE8Qoe9I2OZ3NhryduGNIsRLW1A32TCemsRXZG6h96Sun/YZuEREKCzNR8Kdj35m6Mxj/aBbSE7ALWK3QjHq5Z4SV/UMRGtCRlm/WK+AO10cxSH7E1siud++5ZwtIogFQPZB40uJOlKnIDmyirk8jX2Vojkcy5/xG+HFeUQkXmM1JtAEIhrGOS2hZcs79jqGGEXoCOJ0MSxtdlkh03Z+eu7gJmAel0lrZ9sEv2NxXqDexti+HxYdpDzu4Gwy8d4NjhYMaITjsJyy6v1gQfy8W3bJkCzvb1GpebY3iWS72HUXXrMJ9g="

branches:
  only:
    - master